name: flutter_lover_tale
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #fluuter 현지화
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # fire base
  firebase_core: ^2.0.0
  firebase_auth: ^4.1.3
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.1.0
  firebase_messaging: ^14.9.4

  # google 인증
  google_sign_in: ^5.4.2

  # 권한
  permission_handler: ^11.3.1

  # 글로벌 변수 관리
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg