name: flutter_lover_tale
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #fluuter 현지화
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # fire base
  firebase_core: ^2.0.0
  firebase_auth: ^4.1.3
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.1.0
  firebase_messaging: ^14.9.4

  # google 인증
  google_sign_in: ^5.4.2

  # apple 인증
  sign_in_with_apple: ^6.1.1

  # kakao 인증
  kakao_flutter_sdk_user: ^1.3.1

  # 권한
  permission_handler: ^11.3.1

  # 글로벌 변수 관리
  provider: ^6.0.1

  # 이미지
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6
  flutter_svg: ^2.0.9

  #디자인 관련
  animated_flip_counter: ^0.3.4
  dynamic_tabbar: ^1.0.7

  #uuid
  uuid: ^4.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/common/
    - assets/common/main/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 700