name: flutter_lover_tale
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #fluuter 현지화
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6

  # fire base
  firebase_core: ^2.0.0
  firebase_auth: ^4.1.3
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.1.0

  # google 인증
  google_sign_in: ^5.4.2

  # apple 인증
  sign_in_with_apple: ^6.1.1

  # kakao 인증
  kakao_flutter_sdk_user: ^1.3.1

  # 권한
  permission_handler: ^11.3.1

  # 글로벌 변수 관리
  provider: ^6.0.1

  # 이미지
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6
  flutter_svg: ^2.0.9

  # 디자인 관련
  animated_flip_counter: ^0.3.4
  dynamic_tabbar: ^1.0.7

  # uuid
  uuid: ^4.4.2

  # 앱 아이콘
  flutter_launcher_icons: ^0.13.1

  # 캐러셀
  flutter_image_slideshow: any
  card_swiper: ^3.0.1

  # 캘린더
  flutter_neat_and_clean_calendar: ^0.4.13

  # 광고
  google_mobile_ads: ^5.1.0

  # 토스트
  animated_snack_bar: ^0.4.0

# COMMAND :  "flutter pub run flutter_launcher_icons:main"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/common/logo/lover_tale_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/common/
    - assets/common/logo/
    - assets/common/main/
    - assets/common/icon/
    - assets/common/text/
    - assets/common/character/
    - assets/common/etc/
    - assets/common/emoji/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 700